site:
  component: '@sls-next/serverless-component@1.17'
  inputs:
    policy: arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

UsersTable:
  component: '@serverless/aws-dynamodb'
  inputs:
    name: Users

UsersSessionsTable:
  component: '@serverless/aws-dynamodb'
  inputs:
    name: UsersSessions
    attributeDefinitions:
      - AttributeName: fixtureId
        AttributeType: S
      - AttributeName: userId
        AttributeType: S
    keySchema:
      - AttributeName: fixtureId
        KeyType: HASH
      - AttributeName: userId
        KeyType: RANGE
